name: docker-publish

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags: ['**']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Get tag
        id: preparetag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
        
      - name: Check tag
        run: echo ${{ steps.preparetag.outputs.tag }}
        
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: 14

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
          
      - uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT_HW_DIAG }}
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: mcraa/hardware-diagnostics:latest,mcraa/hardware-diagnostics:${{ steps.preparetag.outputs.tag }}
        
        
      
        
